In [28]:
import pandas as pd
import re

In [29]:
df = pd.read_csv('../data/Dataset_articles_NoID.csv')

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 313320 entries, 0 to 313319
Data columns (total 8 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   URL        313320 non-null  object
 1   Title      313320 non-null  object
 2   Summary    313140 non-null  object
 3   Contents   307763 non-null  object
 4   Date       313320 non-null  object
 5   Author(s)  312499 non-null  object
 6   Category   313320 non-null  object
 7   Tags       313320 non-null  object
dtypes: object(8)
memory usage: 19.1+ MB

In [31]:
# check null
df.isnull().sum()

URL             0
Title           0
Summary       180
Contents     5557
Date            0
Author(s)     821
Category        0
Tags            0
dtype: int64

In [32]:
df = df.dropna(ignore_index=True)

In [33]:
df.isnull().sum()

URL          0
Title        0
Summary      0
Contents     0
Date         0
Author(s)    0
Category     0
Tags         0
dtype: int64

In [34]:
df.head()

,URL,Title,Summary,Contents,Date,Author(s),Category,Tags
0,https://laodong.vn/bat-dong-san/thong-tin-ngoc...,"Thông tin “Ngọc Trinh mua đất ở Bảo Lộc"" chỉ l...","Lâm Đồng - Lãnh đạo thành phố Bảo Lộc, Lâm Đồn...","Những ngày vừa qua, trên trang Facebook chính ...","Thứ sáu, 20/05/2022 08:56 (GMT+7)",Phương Nhiên,Bất động sản,"['Lâm Đồng', 'Ngọc Trinh', 'Chiêu trò', 'Giá đ..."
1,https://laodong.vn/bat-dong-san/lo-hong-trong-...,Lỗ hổng trong việc thẩm tra năng lực tài chính...,TPHCM - Việc không thể cưỡng chế thuế của hai ...,"Theo thông tin từ Cục Thuế TP.HCM, hiện cơ qua...","Thứ sáu, 20/05/2022 08:10 (GMT+7)",Gia Miêu,Bất động sản,"['Thủ Thiêm', 'Đấu giá đất']"
2,https://laodong.vn/bat-dong-san/som-hoan-thien...,Sớm hoàn thiện các dự án nhà ở xã hội để CNLĐ ...,"Hiện trên địa bàn tỉnh Ninh Bình có 32 khu, cụ...",CNLĐ mong muốn sớm được tiếp cận với nhà ở xã ...,"Thứ sáu, 20/05/2022 07:47 (GMT+7)",NGUYỄN TRƯỜNG,Bất động sản,"['Dự án', 'Nhà ở xã hội', 'Dự án nhà ở xã hội'..."
3,https://laodong.vn/bat-dong-san/chi-tiet-ho-so...,Chi tiết hồ sơ hoàn công nhà ở năm 2022,Hoàn công nhà ở với ý nghĩa là điều kiện để đư...,Hoàn công nhà ở là một thủ tục hành chính tron...,"Thứ sáu, 20/05/2022 06:44 (GMT+7)",Kim Nhung (T/H),Bất động sản,"['Giấy phép xây dựng', 'Hồ sơ hoàn công', 'nhà..."
4,https://laodong.vn/bat-dong-san/khoi-tao-khong...,"Khởi tạo không gian sống đẳng cấp, đón sóng đầ...",Có rất nhiều lý do khiến những dự án thấp nội ...,Đi dọc đường Lê Văn Lương kéo dài xuống khu Dư...,"Thứ năm, 19/05/2022 15:30 (GMT+7)",Huyền Nguyễn,Bất động sản,['An Quý Villa']

In [35]:
# drop columns not use
columns = ['URL', 'Tags', 'Author(s)', 'Date']
df.drop(columns=columns, inplace=True)

In [36]:
df.head()

,Title,Summary,Contents,Category
0,"Thông tin “Ngọc Trinh mua đất ở Bảo Lộc"" chỉ l...","Lâm Đồng - Lãnh đạo thành phố Bảo Lộc, Lâm Đồn...","Những ngày vừa qua, trên trang Facebook chính ...",Bất động sản
1,Lỗ hổng trong việc thẩm tra năng lực tài chính...,TPHCM - Việc không thể cưỡng chế thuế của hai ...,"Theo thông tin từ Cục Thuế TP.HCM, hiện cơ qua...",Bất động sản
2,Sớm hoàn thiện các dự án nhà ở xã hội để CNLĐ ...,"Hiện trên địa bàn tỉnh Ninh Bình có 32 khu, cụ...",CNLĐ mong muốn sớm được tiếp cận với nhà ở xã ...,Bất động sản
3,Chi tiết hồ sơ hoàn công nhà ở năm 2022,Hoàn công nhà ở với ý nghĩa là điều kiện để đư...,Hoàn công nhà ở là một thủ tục hành chính tron...,Bất động sản
4,"Khởi tạo không gian sống đẳng cấp, đón sóng đầ...",Có rất nhiều lý do khiến những dự án thấp nội ...,Đi dọc đường Lê Văn Lương kéo dài xuống khu Dư...,Bất động sản

In [37]:
# processed text
def processed(text: str)->str:

    text = re.sub(r'[^\w\s]', '', text)

    text = re.sub(r'\s+', ' ', text).strip()

    return text

In [38]:
df['Title'] = df['Title'].apply(processed)
df['Category'] = df['Category'].apply(processed)
df['Contents'] = df['Contents'].apply(processed)
df['Summary'] = df['Summary'].apply(processed)

In [39]:
df['Combined'] = df['Title'] + '[SEP]' + df['Contents'] + '[SEP]' + df['Category']
df = df.drop(columns=['Title', 'Category', 'Contents'])

In [40]:
from pyvi import ViTokenizer

In [ ]:
df['Combined'] = df['Combined'].apply(ViTokenizer.tokenize)
df['Summary'] = df['Summary'].apply(ViTokenizer.tokenize)

In [ ]:
df.head()

In [ ]:
from torch.utils.data import Dataset
import torch
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained('vinai/bartpho-word')

class BartPhoDataset(Dataset):
    def __init__(self, df, tokenizer, max_source_len=512, max_target_len=128):
        self.text_list = df['Combined'].values
        self.summary = df['Summary'].values
        self.tokenizer = tokenizer
        self.max_source_len = max_source_len
        self.max_target_len = max_target_len

    def __len__(self):
        return len(self.text_list)

    def __getitem__(self, idx):
        text = str(self.text_list[idx])
        summary = str(self.summary[idx])

        encoding_text = self.tokenizer(
            text,
            add_special_tokens=True, 
            max_length=self.max_source_len,
            padding='max_length',    
            truncation=True,         
            return_attention_mask=True, 
            return_tensors='pt',
        )

        encoding_summary = self.tokenizer(
            summary,
            add_special_tokens=True, 
            max_length=self.max_target_len,
            padding='max_length',    
            truncation=True,         
            return_attention_mask=True, 
            return_tensors='pt',
        )

        labels = encoding_summary['input_ids'].flatten()

        labels[labels == self.tokenizer.pad_token_id] = -100

        return {
            # .flatten() để làm phẳng tensor từ kích thước [1, max_len] thành [max_len]
            'input_ids': encoding_text['input_ids'].flatten(),
            'attention_mask': encoding_text['attention_mask'].flatten(),
            'labels': labels,
        }

In [ ]:
dataset = BERTDataset(df, tokenizer)

In [ ]:
dataset[0]

{'input_ids': tensor([    0,  4848,   200,  2265,  5090,   188,   179,    25,  4162,  3375,
            66,     8,  4065,  2680,  3675,   133, 27979,  1187, 63576,  7260,
          1186,     3,   217,    43,   164,    89,    34,   751,  1168,   159,
           286,     7,  2265,  5090,    10,  1813,  2274,  2178,   200,    18,
           585,    23,   164,   188,  7086,   953,   179,    15, 21315,    35,
           176,  3449,  1721,  8656,  4162,  3375,   369,  1451,    61,  1393,
          2198,   103,    39,   553,   705,  2405,    80,   289,   162,    37,
            16,   100,   751,  2178,   200,     6,   289,   176,  1093,    85,
           917,  9170,  1813,    35,    44,  2178,   200,    23,    80,   790,
         50351,  2608,   316,   179,  2265,  5090,    60,   188,   339,    35,
           176,  3449,  1721,  8656,  4162,  3375,  1187, 18020,  1517,  3531,
            25,   626,  5924, 14307,  4439,   917,  2956,   778,     6,    10,
          1660,  3258,  2400, 12083,   592,   551,   543,  2288,    13,   560,
           915,  1885,  1471,  1382,    13,  5963,   336,   347,  2178,   200,
            23,    46,  1037,  1816,  6792,  3698, 26865,   264,   302,   835,
          4162,  3375,    13,    55,   264,   302,   835,    14,   413,   630,
          2209,  2665,  1766,  7038,     6,   264,   176,  3449,  1721,  5438,
          2288,  7303,  3011,  2178,   200,  1326,  2906,  9534,   316,   179,
          2265,  5090,   690,   819,     6,  1813,  2274,    72,   289,   176,
          1093,   187,  6079,  4702, 14658,  3075,   870, 19359,   176,  3449,
          1721,   293,    97,    17,    41,     8,   179,  1251,  2289, 21315,
             7,  2265,  5090,    92,     9,  1005,  6829,  2183,  9170,  2657,
          2665,   179,  9689,    34,  4439,   509,   176,  3449,  1721,    17,
            10,   286,  1362,   142,   221,     8,  3212,  6966,  2265,  5090,
           221,   520,     7,  2265,  5090,  7635,    85,  7328,    94,     9,
           930,   565,  1251,  2289, 21315,     2]),
 'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 'labels': tensor([    0,  2521,  2316, 19703,  2477,   302,   835,  4162,  3375,  2521,
          2316, 50351,  2608,  2178,   200,    18,   585,  2265,  5090,   188,
          7086,   953,   179,    25,  4439,  1607,    24,    47, 21315,     8,
          4456,   668,  1069,    61,   520,   669,    66,     8,  4065,  2680,
             7,   681,  5408,  2697,  4770,    24,  3675,   133,   179,     2,
          -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
          -100,  -100,  -100,  -100])}